#!/bin/bash
#
# .claude/hooks/verify.sh — Stop-hook verification gate (v6)
#
# Claude Code runs this every time the agent tries to end its turn.
#   Exit 2 -> blocked; stderr below is fed back to Claude, which must keep working.
#   Exit 0 -> allowed to stop.
#
# Checks run cheapest-first. An EMPTY command is skipped, so the gate is useful
# on day one (lint + build) and grows with the project (smoke, then tests).
#
# Verified-state cache: after a green run we fingerprint the working tree + the
# check commands. A later turn that leaves that exact state untouched skips the
# whole suite, so dirty-but-unchanged turns (explanations, follow-up Q&A after a
# green task) don't re-run lint/build/tests.
#
# Misconfig fast-fail: a check that can't even run (missing script/tool, no
# browser, no project file) escalates immediately — retrying can't fix a
# misconfigured gate, so we don't waste MAX_ATTEMPTS of slow re-runs on it.
#
# Escalation: on the final failed attempt we block ONE more time with
# instructions to report the failure honestly, then allow that wrap-up turn to
# end. We deliberately do NOT skip when stop_hook_active is true — that would
# let unverified "fixes" through. The attempt counter is the loop guard.

INPUT=$(cat)  # hook JSON on stdin
SESSION_ID=$(printf '%s' "$INPUT" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
[ -n "$SESSION_ID" ] || SESSION_ID="default"

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0

# ---- Commands come from .claude/verify.config (generated by install.sh from ----
# ---- stack detection; project-owned, survives --force). Empty = skipped;    ----
# ---- no config file at all = every check skipped (gate inert, not an error). ----
LINT_CMD=""; BUILD_CMD=""; SMOKE_CMD=""; TEST_CMD=""
[ -f ./.claude/verify.config ] && . ./.claude/verify.config

MAX_ATTEMPTS=3
STATE_DIR="${TMPDIR:-/tmp}/claude-verify"
mkdir -p "$STATE_DIR"
COUNTER_FILE="$STATE_DIR/$SESSION_ID"   # per-session: no cross-session/worktree bleed
VERIFIED_FILE="$COUNTER_FILE.ok"        # fingerprint of the last tree state that passed
STATE=$(cat "$COUNTER_FILE" 2>/dev/null || echo 0)

# Claude already wrote its honest failure report last turn — let it end now.
if [ "$STATE" = "escalated" ]; then
  rm -f "$COUNTER_FILE" "$VERIFIED_FILE"
  exit 0
fi

IN_GIT=false
git rev-parse --is-inside-work-tree >/dev/null 2>&1 && IN_GIT=true

# Nothing changed (pure Q&A turn) -> don't make the dev sit through the checks.
# A clean tree is also a task boundary, so drop the verified fingerprint.
if [ "$IN_GIT" = true ] && [ -z "$(git status --porcelain 2>/dev/null)" ]; then
  rm -f "$COUNTER_FILE" "$VERIFIED_FILE"
  exit 0
fi

# Fingerprint of everything the checks would see: tracked changes vs HEAD, the
# porcelain status (renames/deletes/untracked paths), the content of untracked
# files, and the check commands themselves (editing verify.config re-verifies).
# Assumes build output (node_modules, bin/obj) is gitignored — true in every
# Angular/.NET repo. Hashed with git itself, so no dependency beyond the git the
# hook already needs. Cheap next to a full build.
tree_fingerprint() {
  {
    git diff HEAD 2>/dev/null
    git status --porcelain 2>/dev/null
    git ls-files --others --exclude-standard -z 2>/dev/null \
      | while IFS= read -r -d '' f; do printf '%s:' "$f"; git hash-object "$f" 2>/dev/null; done
    printf 'CMDS:%s|%s|%s|%s\n' "$LINT_CMD" "$BUILD_CMD" "$SMOKE_CMD" "$TEST_CMD"
  } | git hash-object --stdin 2>/dev/null
}

# If this exact tree + these exact commands already passed this session, the
# result can't have changed -> skip the whole suite. The big win: a dirty tree
# left untouched since the last green run no longer re-pays for lint/build/tests.
FP=""
if [ "$IN_GIT" = true ]; then
  FP=$(tree_fingerprint)
  if [ -n "$FP" ] && [ "$FP" = "$(cat "$VERIFIED_FILE" 2>/dev/null)" ]; then
    rm -f "$COUNTER_FILE"
    exit 0
  fi
fi

ATTEMPTS=$STATE
case "$ATTEMPTS" in *[!0-9]*|'') ATTEMPTS=0 ;; esac

LOG=$(mktemp)
trap 'rm -f "$LOG"' EXIT

# Signatures of a check that COULDN'T RUN (missing npm script, tool not on PATH,
# no browser for karma, no/ambiguous .csproj) rather than one that ran and found
# a real code problem. Matched case-insensitively against the failing check's
# own output only. Exit 126/127 (not executable / not found) counts too.
MISCONFIG=""
MISCONFIG_RE='missing script|not recognized as an internal|no binary for .*browser|cannot start chrome|chrome failed [0-9]|failed to launch the browser|no usable sandbox|msb1003|msb1009|specify (a|which) project or solution|could not execute because the specified command|no test projects were found'

# Lines that actually name a failure: TS/Angular/C#/MSBuild compiler codes,
# webpack/esbuild errors, and karma/jasmine/xunit test failures. Used to pull
# the real cause to the front of the report (build tools bury it under summary).
FAIL_RE='error (TS|NG|CS|MSB)[0-9]|ERROR in|✘ \[ERROR\]|Build FAILED|Failed!|\[FAIL\]|FAILED|✗ |Expected .+ (to|but)|AssertionError|[0-9]+ (failing|failed)'

run_check() {  # $1 label, $2 command; empty command = skip
  [ -z "$2" ] && return 0
  local out rc
  out=$(mktemp)
  { echo ""; echo "== $1: $2"; } >>"$LOG"
  eval "$2" >"$out" 2>&1
  rc=$?
  cat "$out" >>"$LOG"
  if [ "$rc" -ne 0 ] && { [ "$rc" -eq 126 ] || [ "$rc" -eq 127 ] || grep -qiE "$MISCONFIG_RE" "$out"; }; then
    MISCONFIG="Check '$1' (\`$2\`) exited $rc without producing a real verdict — a missing tool/script or a misconfigured command, not a code failure."
  fi
  rm -f "$out"
  return "$rc"
}

# Report the lines that name the failure first (with a little trailing context),
# so the real error isn't lost under a build tool's trailing summary. Falls back
# to a plain tail when nothing matches the signatures.
failure_excerpt() {  # $1 = fallback tail length
  local hits
  hits=$(grep -E -A2 "$FAIL_RE" "$LOG" 2>/dev/null | head -n 50)
  if [ -n "$hits" ]; then
    echo "---- failure lines (a full tail follows only if these miss it) ----"
    printf '%s\n' "$hits"
  else
    tail -n "$1" "$LOG"
  fi
}

if run_check "lint"  "$LINT_CMD"  && \
   run_check "build" "$BUILD_CMD" && \
   run_check "smoke" "$SMOKE_CMD" && \
   run_check "tests" "$TEST_CMD"; then
  # Certify this state so an untouched later turn can skip the suite.
  [ -n "$FP" ] && printf '%s\n' "$FP" > "$VERIFIED_FILE"
  rm -f "$COUNTER_FILE"
  exit 0
fi

# A check that couldn't run won't fix itself on retry. Escalate in one step:
# block once (so Claude sees exactly what's wrong), and set the escalated state
# so the next turn is allowed to end instead of looping on an unfixable error.
if [ -n "$MISCONFIG" ]; then
  echo "escalated" > "$COUNTER_FILE"
  rm -f "$VERIFIED_FILE"
  {
    echo "VERIFICATION GATE MISCONFIGURED — this is NOT a code problem. Do not retry or edit app code to chase it."
    echo "$MISCONFIG"
    echo "Fix the command in .claude/verify.config (correct it, or empty it to skip that"
    echo "check) or install the missing tool, then tell the user the gate needed attention."
    echo ""
    tail -n 30 "$LOG"
  } >&2
  exit 2
fi

ATTEMPTS=$((ATTEMPTS + 1))

if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
  echo "escalated" > "$COUNTER_FILE"
  {
    echo "Verification has failed $MAX_ATTEMPTS times on this task. STOP attempting fixes."
    echo "In your next reply: state plainly that the task is NOT complete, summarize what"
    echo "is failing and what you tried, and hand it to the user for review. Failure:"
    echo ""
    failure_excerpt 40
  } >&2
  exit 2
fi

echo "$ATTEMPTS" > "$COUNTER_FILE"
{
  echo "Verification failed (attempt $ATTEMPTS of $MAX_ATTEMPTS). Do not report this task"
  echo "as done. Fix the root cause shown below, then finish again:"
  echo ""
  failure_excerpt 60
} >&2
exit 2
